apiVersion: v1
kind: Service
metadata:
  name: course-service
  labels:
    app: course-service
spec:
  selector:
    app: course-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer