version: '3'

# List of services
services:
  admin-service: # Uadminser service configuration
    image: kalingajayathilaka/adminservice:latest
    ports:
      - "5001:5001"

  course-service: # course service configuration
    image: kalingajayathilaka/courseservice:latest
    ports:
      - "5000:5000"

  email-service: # email service configuration
    image: kalingajayathilaka/emailservice:latest
    ports:
      - "9123:9123"

  learner-service: # learner service configuration
    image: kalingajayathilaka/learnerservice:latest
    ports:
      - "5003:5003"

  sms-service: # sms service configuration
    image: kalingajayathilaka/smsservice:latest
    ports:
      - "3001:3001"

  user-service: # user service configuration
    image: kalingajayathilaka/userservice:latest
    ports:
      - "5002:5002"

  # Frontend service configuration  
  frontend:
    image: kalingajayathilaka/frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - admin-service
      - course-service
      - email-service
      - learner-service
      - user-service
      - sms-service