apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-service
  labels:
    app: sms-service
spec:
  replicas: 1 # Copies of each pod to run
  selector:
    matchLabels:
      app: sms-service
  template:
    metadata:
      labels:
        app: sms-service
    spec:
      containers:
        - name: sms-service
          image: smsservice:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
