apiVersion: v1
kind: Service
metadata:
  name: sms-service
  labels:
    app: sms-service
spec:
  selector:
    app: sms-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer