apiVersion: v1
kind: Service
metadata:
  name: learner-service
  labels:
    app: learner-service
spec:
  selector:
    app: learner-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: LoadBalancer